apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: employee-platform
  annotations:
    iam.gke.io/gcp-service-account: external-secrets@cloudappproject-494314.iam.gserviceaccount.com
