apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: employee-platform
spec:
  provider:
    gcpsm:
      projectID: "863212817133"
      auth:
        workloadIdentity:
          clusterLocation: europe-west1
          clusterName: dev-cloud-native-employee-gke
          serviceAccountRef:
            name: external-secrets-sa
