apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: employee-platform
spec:
  provider:
    gcpsm:
      projectID: cloudappproject-494314
      auth:
        workloadIdentity:
          clusterLocation: europe-west1
          clusterName: employee-gke
          serviceAccountRef:
            name: external-secrets-sa
