apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: employee-platform-secret
  namespace: employee-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: gcp-secret-manager
  target:
    name: employee-platform-secret
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: employee-platform-mysql-root-password
    - secretKey: DB_PASSWORD
      remoteRef:
        key: employee-platform-db-password
    - secretKey: JWT_SECRET
      remoteRef:
        key: employee-platform-jwt-secret
